DWAPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 2.0
    acc_lim_y: 0.0
    acc_lim_th: 10.0
    
    max_vel_trans: 1.0
    min_vel_trans: 0.1

    max_vel_x: 4.0
    min_vel_x: -0.5
    max_vel_y: 0.0
    min_vel_y: 0.0

    max_rot_vel: 13.0
    min_rot_vel: 1.0

    # Goal Tolerance Parameters
    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    sim_time: 2.0
    sim_granularity: 0.025
    vx_samples: 3
    vy_samples: 0
    vth_samples: 50
    controller_frequency: 20.0

    # Trajectory Scoring Parameters
    path_distance_bias: 2
    goal_distance_bias: 0.3
    occdist_scale: 0.8
    forward_point_distance: 0.325
    stop_time_buffer: 0.2
    scaling_speed: 0.25
    max_scaling_factor: 1.0
    publish_cost_grid: false
    global_frame_id: odom

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.05

    # Global Plan Parameters
    prune_plan: true
