scan_filter_chain:
  - name: robot_body_filter
    type: laser_filters/LaserScanBoxFilter
    params:
      min_x: -0.3
      max_x: 0.3
      min_y: -0.3
      max_y: 0.3
      min_z: -0.1
      max_z: 0.5
      invert: false

  - name: combined_range_and_clearing_filter
    type: laser_filters/LaserScanRangeFilter
    params:
      lower_threshold: 0.1
      upper_threshold: 4.0 
      use_message_range_limits: false
      lower_replacement_value: .inf 
      upper_replacement_value: 4.1
